name: 'ecommerce'
version: '1.0'

source-paths: ["models"]
analysis-paths: ["analysis"]
target-path: "target"
clean-targets: ["target"]
test-paths: ["test"]
data-paths: ["data"]

models:
    ecommerce:
        vars:
            customers_table: #schema.table
            orders_table: #schema.table
            order_items_table: #schema.table
            skus_table: #schema.table
            products_table: #schema.table
