name: 'ecommerce'
version: '1.0'

source-paths: ["models"]
analysis-paths: ["analysis"]
target-path: "target"
clean-targets: ["target"]
test-paths: ["test"]
data-paths: ["data"]

models:
    ecommerce:
        vars:
            customers_table: dbt_jthandy.customers
            orders_table: dbt_jthandy.orders
            order_items_table: dbt_jthandy.order_items
            skus_table: dbt_jthandy.skus
            products_table: dbt_jthandy.products

profile: metrograph
